version: '3.1'
services:
  mongo:
    image: mongo:latest
    container_name: "mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: demo
      MONGO_INITDB_ROOT_PASSWORD: demo
    volumes:
      - './dockervolume/mongodb:/data/db'
    ports:
      - 27017:27017
